name = "pollinations-hello"
compatibility_date = "2025-11-01"

[[routes]]
pattern = "hello.pollinations.ai"
zone_name = "pollinations.ai"
custom_domain = true

[assets]
directory = "dist"
not_found_handling = "single-page-application"
