name = "pollinations-gsoc-api"
main = "worker.js"
compatibility_date = "2026-01-11"

[env.production]
routes = [
  { pattern = "gsoc.pollinations.ai/api/*", zone_name = "pollinations.ai" }
]

[[triggers.crons]]
cron = "0 0 * * *"
